### ISSUE TITLE
the badges does not show the correct status

### ISSUE THREAD

**Issue by mmatyi** [sckott/cchecksbadges#4]
hello, 

Is the service https://badges.cranchecks.info/ discontinued?
I am asking because it shows incorrect status, either not OK or unknown.
Thank you for your feedback.

**Comment by sckott** [comment]
what package are you asking about? 

the service should be operating normally, but it's possible there's a problem with certain packages.

**Comment by jbryer** [comment]
Here is one: https://badges.cranchecks.info/flavor/release/ggplot2.svg
I tried a bunch of package with a bunch of the `/flavor/` endpoints and none appear to be working.

**Comment by sckott** [comment]
Thanks @jbryer i'll check it out

**Comment by sckott** [comment]
@mmatyi @jbryer should be fixed now - let me know if you see any more problems
