### ISSUE TITLE
https://badges.cranchecks.info/flavor/r-devel-windows-ix86+x86_64/germinationmetrics.svg

### ISSUE THREAD

**Issue by aravind-j** [sckott/cchecksbadges#5]
The names of windows flavours have been updated in [CRAN](https://cran.r-project.org/web/checks/check_flavors.html#r-devel-windows-x86_64).

# Old
```
/flavor/r-devel-windows-ix86+x86_64/:pkg.svg
/flavor/r-oldrel-windows-ix86+x86_64/:pkg.svg
/flavor/r-release-windows-ix86+x86_64/:pkg.svg
```

# New
```
/flavor/r-devel-windows-x86_64/:pkg.svg
/flavor/r-oldrel-windows-x86_64/:pkg.svg
/flavor/r-release-windows-x86_64/:pkg.svg
```

Because of this windows flavour specific badges by `ccheckbadges` are showing 'Unknown/not found' badges.

For example

https://badges.cranchecks.info/flavor/r-devel-windows-ix86+x86_64/germinationmetrics.svg
[![CRAN check - r-devel-windows-ix86+x86_64](https://badges.cranchecks.info/flavor/r-devel-windows-ix86+x86_64/germinationmetrics.svg)](https://cran.r-project.org/web/checks/check_results_germinationmetrics.html)

https://badges.cranchecks.info/flavor/r-release-windows-ix86+x86_64/germinationmetrics.svg
[![CRAN check - r-release-windows-ix86+x86_64](https://badges.cranchecks.info/flavor/r-release-windows-ix86+x86_64/germinationmetrics.svg)](https://cran.r-project.org/web/checks/check_results_germinationmetrics.html)

https://badges.cranchecks.info/flavor/r-oldrel-windows-ix86+x86_64/germinationmetrics.svg
[![CRAN check - r-oldrel-windows-ix86+x86_64](https://badges.cranchecks.info/flavor/r-oldrel-windows-ix86+x86_64/germinationmetrics.svg)](https://cran.r-project.org/web/checks/check_results_germinationmetrics.html)

**Comment by sckott** [comment]
thanks! I'll fix asap

**Comment by sckott** [comment]
building with change now

**Comment by sckott** [comment]
@aravind-j should be fixed, let me know if it's working or not for you
