### ISSUE TITLE
https://badges.cranchecks.info/ expired domain

### ISSUE THREAD

**Issue by mmatyi** [sckott/cchecksbadges#6]
hello, 

for the https://badges.cranchecks.info/ i receive that 

> The domain has expired. Is this your domain? [Renew now](https://www.namecheap.com/domains/registration/results/?domain=Cranchecks.info)

Will you renew and continue or there will be under a new domain?

**Comment by sckott** [comment]
thanks for the report @mmatyi ! I just fixed that - can you try again?

**Comment by mmatyi** [comment]
It works now, thank you.
