### ISSUE TITLE
Summary red badge only with notes???

### ISSUE THREAD

**Issue by iagogv3** [sckott/cchecksbadges#7]
A check badge like https://badges.cranchecks.info/summary/taxize.svg is shown as "Not OK" with red background but the `taxize` CRAN Checks only show OK and Notes, so shouldn't fit that better the Note badge?

**Comment by sckott** [comment]
Thanks for the issue. The way the code is written, badge is "NOT OK" if there's anything other than "OK" across any of the cran checks for that pkg. 

You can do worst to get the badge that says NOTE for the badge

**Comment by iagogv3** [comment]
Thanks for the answer. I've just commented because it sounded strange to me that blue background (NOTE badge) is worse than red background (NOT OK badge)

**Comment by sckott** [comment]
yeah, maybe that is a bit confusing. I don't recall the decisions on the colors now 🤷🏽
